spring:
  application:
    name: lease-demo

  profiles:
    active: local

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 1000ms
      timeout: 500ms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: leasedemo-pdf-mail-v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.leasedemo.lease.application.event

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

application:
  version: 0.1.0

leasedemo:
  mail:
    demo-recipient: ${LEASEDEMO_MAIL_RECIPIENT:customer@leasedemo.local}

  lease:
    default-market: PL

  cache:
    exchange-rates:
      ttl: PT6H
