services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: lease-demo-keycloak

    command: start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8081:8080"
